name: Run Locust Tests on Commit

on:
  push:
    branches:
      - main

jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Start Flask Server
        run: |
          nohup python server.py &
          echo "Waiting for Flask server to start"
          sleep 30

      - name: Run Locust Load Tests
        run: |
          nohup locust -f locustfile.py --headless -u 10000 -r 100 --host=http://localhost:5000 &
          sleep 120
          pkill -f locust

      - name: Stop Flask Server
        run: |
          pkill -f server.py
